spring.application.name=StudentHub
spring.datasource.url=jdbc:mysql://localhost:3306/studenthub
spring.datasource.username=root
spring.datasource.password=Saif2@09

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
